account/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from . import views
from django.urls import reverse_lazy

urlpatterns = [
    path("signup", views.signup, name="signup"),
    path("signin", views.signin, name="signin"),
    path("signout", views.signout, name="signout"),
    path("profile", views.profile, name="profile"),
    path(
        "resetpassword/",
        views.CustomPasswordResetView.as_view(),
        name="resetPassword",
    ),
    path(
        "resetpassworddone/",
        PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
        name="resetPasswordDone",
    ),
    path(
        "resetpasswordconfirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html",
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "resetpasswordcomplete/",
        PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("groups", views.groups_list, name="group-list"),
    path('create-group',views.CreateDynamicGroup,name='create-group')

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls")),
    path("account/", include("account.urls")),
    path("apce/", include("Adminuser.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from .validators import validate_phone_number


class CustomUser(AbstractUser):
    email = models.EmailField(max_length=100, unique=True)
    username = models.CharField(
        blank=True,
        null=True,
        max_length=10,
        unique=True,
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def save(self, *args, **kwargs):
        self.email = self.email.lower()
        return super().save(*args, **kwargs)

    def get_profile(self):
        return UserProfile.objects.get_or_create(user=self)[0]


class UserProfile(models.Model):
    GENDER_CHOICES = [
        ("male", "Male"),
        ("female", "Female"),
    ]

    DEPARTEMENT = [
        ("Computer science", "Computer science"),
        ("Civil", "Civil"),
        ("Mechanical", "Mechanical"),
        ("ECE", "ECE"),
        ("EEE", "EEE"),
        ("IT", "IT"),
        ("Cyber security", "Cyber security"),
        ("AIDS", "AIDS"),
    ]

    YEAR = [
        ("First year", "First year"),
        ("Second year", "Second year"),
        ("Third year", "Third year"),
        ("Final year", "Final year"),
    ]

    PASSEDOUT_YEAR = [
        ("2025", "2025"),
        ("2026", "2026"),
        ("2027", "2027"),
        ("2028", "2028"),
        ("2029", "2029"),
        ("2030", "2030"),
        ("2031", "2031"),
        ("2032", "2032"),
        ("2033", "2033"),
    ]

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, null=True, blank=True)
    phone_number = models.CharField(
        max_length=15,
        null=True,
        blank=True,
        validators=[validate_phone_number],
    )
    gender = models.CharField(
        max_length=6,
        choices=GENDER_CHOICES,
        null=True,
        blank=True,
    )
    department = models.CharField(
        max_length=17,
        choices=DEPARTEMENT,
        null=True,
        blank=True,
    )
    year = models.CharField(
        max_length=17,
        choices=YEAR,
        null=True,
        blank=True,
    )
    passedout_year = models.CharField(
        max_length=4,
        choices=PASSEDOUT_YEAR,
        null=True,
        blank=True,
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    aadhar_number = models.CharField(max_length=12, null=True, blank=True)
    father_name = models.CharField(max_length=30, null=True, blank=True)
    mother_name = models.CharField(max_length=30, null=True, blank=True)
    father_occupation = models.CharField(max_length=50, null=True, blank=True)
    mother_occupation = models.CharField(max_length=30, null=True, blank=True)
    father_phone_number = models.CharField(max_length=15, null=True, blank=True)
    mother_phone_number = models.CharField(max_length=15, null=True, blank=True)
    annual_income = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
    )
    religion = models.CharField(max_length=50, null=True, blank=True)
    caste = models.CharField(max_length=50, null=True, blank=True)
    community = models.CharField(max_length=50, null=True, blank=True)
    mother_language = models.CharField(max_length=50, null=True, blank=True)


    def __str__(self):
        return self.user.email
    
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.user.username
        super(UserProfile, self).save(*args, **kwargs)


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()


@receiver(post_save, sender=CustomUser)
def save_username_when_user_is_created(sender, instance, created, **kwargs):
    if created:
        email = instance.email
        sliced_email = email.split("@")[0]
        instance.username = sliced_email
        instance.save()

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser, UserProfile


class signup_from(UserCreationForm):
    email = forms.EmailField(max_length=100, label="email")

    class Meta:
        model = CustomUser
        fields = ["email", "password1", "password2"]


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())


class profile_form(forms.ModelForm):
    # date_of_birth = forms.DateField(widget= AdminDateWidget)
    class Meta:
        model = UserProfile
        exclude = ["user"]

    def __init__(self, *args, **kwargs):
        super(profile_form, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input-form"
            field.label = UserProfile._meta.get_field(field_name).verbose_name
            field.widget.attrs["placeholder"] = f"Enter your {field.label}"

account/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from .forms import *
from django.contrib.auth import (
    authenticate,
    login,
    logout,
)
from django.contrib import messages
from myapp.decorators import authenticate_users
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from .models import *


def signup(request):
    form = signup_from()
    if request.method == "POST":
        form = signup_from(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password1"]
            user = authenticate(email=email, password=password)
            login(request, user)
            messages.success(
                request,
                "your are signed in successfully",
            )
            return redirect("home")
    else:
        form = signup_from()

    return render(
        request,
        "register.html",
        {"form": form},
    )


def signin(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST)
        email = form.data["email"]
        password = form.data["password"]
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(
                request,
                "your are logged in successfully",
            )
            return redirect("home")
        else:
            form.add_error(None, _("invalid credentials"))
            # return redirect('signin')
    print(form.non_field_errors())
    return render(request, "login.html", {"form": form})


def signout(request):
    logout(request)
    messages.success(request, "you have been logged out")
    return redirect("home")


@authenticate_users
def profile(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = None

    if request.method == "POST":
        form = profile_form(request.POST, instance=user_profile)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect("profile")
    else:
        form = profile_form(instance=user_profile)

        return render(
            request,
            "profile.html",
            {
                "form": form,
            },
        )


class CustomPasswordResetView(PasswordResetView):
    template_name = "password_reset.html"
    success_url = reverse_lazy("resetPasswordDone")

account/templates/login.html
{% extends 'home.html' %}
{% block main %}
<div class="form-page">
    <div class="d2h-container">
        <h1 class="dare">CSE</h1>
        <h1 class="two"></h1>
        <h2 class="hack">IANS</h2>
    </div>
    <div class="form-container">
        <form action="{% url 'signin' %}" method="post" class="form backdrop-blur-sm">
            {% csrf_token %}
            {{form}}
            <input type="hidden" name="next" value="{% if next %}{{next}}{% else %}{% url 'home' %}{% endif %}">
            <div class="flex justify-between items-center">
                <input type="submit" value="login" class=" bg-red-600 border-[1px] hover:cursor-pointer text-sm font-inter text-white px-2">
                <a href="{% url 'resetPassword' %}" class="text-white hover:cursor-pointer  underline text-sm md:text-red-800">Forget password?</a>
            </div>
              </button>
            <p class="mt-4 text-[12px] text-slate-100 md:text-black">Don't have an account? <a href="{% url 'signup' %}?next={{request.GET.next}}" class="text-white underline text-[13px] ml-2 md:text-red-800">Register</a></p>
        </form>
    </div>
</div>

{% endblock %}

account/templates/password_reset.html
{% extends  'home.html' %}
{% block main %}

<div class="form-page">
    <div class="d2h-container">
        <h1 class="dare" >CSE</h1>
        <h1 class="two"></h1>
        <h2 class="hack">IANS</h2>
    </div>
    <div class="form-container">
        <form action="{% url 'resetPassword' %}" method="post" class="form">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Reset" class="btn p-1">
        </form>
    </div>
</div>

{% endblock %}

account/templates/password_reset_complete.html
{% extends 'home.html' %}
{% block main %}

<div class="form-page">
    <div class="d2h-container">
        <h1 class="dare" >CSE</h1>
        <h1 class="two">2</h1>
        <h2 class="hack">BOYS</h2>
    </div>
    <div class="text-container">
        <h1>
            Password reset complete
        </h1>
        <p>
            Your password has been set. You may go ahead and log in now.
        </p>
        <a href="{% url 'signin' %}" class="text-blue-400">login</a>
    </div>
</div>

{% endblock %}

account/templates/password_reset_confirm.html
{% extends 'home.html' %}
{% block main %}

<div class="form-page">
    <div class="d2h-container">
        <h1 class="dare" >CSE</h1>
        <h1 class="two">2</h1>
        <h2 class="hack">HACK</h2>
    </div>
    <div class="form-container">
        <form method="post" class="form">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Reset Password" class="btn p-1">
        </form>
    </div>
</div>

{% endblock %}

account/templates/password_reset_done.html
{% extends  'home.html' %}
{% block main %}

<div class="form-page">
    <div class="d2h-container">
        <h1 class="dare" >CSE</h1>
        <h1 class="two">2</h1>
        <h2 class="hack">HACK</h2>
    </div>
    <div class="text-container">
        <h1>Password reset sent</h1>
        <p>
            We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
            If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
            After reseting the password login with the below link:
        </p>
        <a href="{% url 'signin' %}" class="text-red-500">login</a>
    </div>
</div>

{% endblock %}

account/templates/profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

<head>
  {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'profile.css' %}">
  {% endblock %}
</head>
<body>
    {% block content %}
    
    <a href="{% url 'home' %}" style="text-decoration: none; color: black;">
        <img src="{% static 'icons/arrow.png' %}" alt="" width="25px"> 
        <span style="font-size: 18px; text-decoration: none;">home</span>
    </a> 
    <br>
    <img src="{% static 'photos/Banner 1.svg' %}" alt="" width="100%" height="40%">
    
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-container">
          <div class="form-section-one">
            <label for="id_name">Name:</label>
            {{ form.name }}
            <label for="id_phone_number">Phone Number:</label>
            {{ form.phone_number }}
            <label for="id_gender">Gender:</label>
            {{ form.gender }}
            <label for="id_department">Department:</label>
            {{ form.department }}
            <label for="id_year">Year:</label>
            {{ form.year }} 
            <label for="id_address">Address:</label>
            {{ form.address }}
            <label for="id_aadhar_number">Aadhar Number:</label>
            {{ form.aadhar_number }}
            <label for="id_father_name">Father Name:</label>
            {{ form.father_name }}
            <label for="id_mother_name">Mother Name:</label>
            {{ form.mother_name }}
            
          </div>
          
          <div class="form-section-two">
            <label for="id_passedout_year">Passed Out Year:</label>
            {{ form.passedout_year }} 
            <label for="id_father_occupation">Father Occupation:</label>
            {{ form.father_occupation }}
            <label for="id_mother_occupation">Mother Occupation:</label>
            {{ form.mother_occupation }}
            <label for="id_father_phone_number">Father Phone Number:</label>
            {{ form.father_phone_number }}
            <label for="id_mother_phone_number">Mother Phone Number:</label>
            {{ form.mother_phone_number }}
            <label for="id_annual_income">Annual Income:</label>
            {{ form.annual_income }}
            <label for="id_religion">Religion:</label>
            {{ form.religion }}
            <label for="id_caste">Caste:</label>
            {{ form.caste }}
            <label for="id_community">Community:</label>
            {{ form.community }}
            <label for="id_mother_language">Mother Language:</label>
            {{ form.mother_language }}
            <br>
            <button type="submit" class="btn btn-secondary p-3">Save</button>
          </div>
        </div>
    </form>
    {% endblock %}
</body>
</html>

account/templates/register.html
{% extends 'home.html' %}
{% block main %}
<div class="form-page">
    <div class="d2h-container">
        <h1 class="dare" >CSE</h1>
        <h1 class="two"></h1>
        <h2 class="hack">IANS</h2>
    </div>
    <div class="form-container text-sm bg-white rounded-xl bg-opacity-10 backdrop-filter backdrop-blur-sm ">
        <form action="{% url 'signup' %}" method="post" class="form">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Register" class="bg-red-600 text-white text-sm font-inter font-bold px-2 ">
            <div class="flex flex-col md:flex-row mt-4">
                <div class="flex ">
                    <p class="w-[70%] text-[12px] md:mr-3">Already having account?</p>
                    <div class="w-[40%] "><a href="{% url 'signin' %}" class="underline text-red-800 text-[12px] ">try login</a></div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}